### ISSUE TITLE
設計

### ISSUE THREAD

**Issue by tochiman** [tochiman/ticketing-system#1]
Markdown形式でよろしく。

**Comment by JunFujik** [comment]
# 店側
- 商品の登録
    - 名前
    - 価格
    - 概要
    - 写真
    - アレルギー
    - サイズ(S,M,L)
    - カテゴリ
    - 在庫数
- オーガナイゼーション機能
    - 複数店舗を見据えて
    - 店舗ごとに在庫やメニューを分ける機能
        - 「会社名・店舗」で分ける
- QRコードの生成
    - ハッシュなど
    - 送信機能
- QRコードの読み取り
    - 照合
- 販売数(在庫管理)
- 決済機能

# 客
- ユーザ機能
    - ID,PW
    - 注文ログ
    - 決済手段登録(カード情報など)
- 店検索
    - 文字
    - マップ(現在地に近い店舗)

**Comment by tochiman** [comment]
あとでDocフォルダ作ってそこにPDF形式？で載せたい予定

**Comment by tochiman** [comment]
# 使用する技術
## frontend
- Svelte
## QRCode
- svelte-qrcode
[参考](https://github.com/kofkuiper/svelte-scan-qrcode?tab=readme-ov-file)
## backend
- python(FastAPI)

## DB
- MariaDB
## environment
- docker

**Comment by tochiman** [comment]
# 決済をどこの会社を通して行うか
[参考](https://www.aspicjapan.org/asu/article/7298)

**Comment by JunFujik** [comment]
## 流れ
0. 店：メニューを事前にサイトに登録。
1. 客：ログイン -> お店を検索
2. 客：選んだお店のメニューから注文する。
店：注文に対応したQRコードを生成しユーザに送信。
3. 客：お店に行ってQRコードを出す。
店：QRコードをスキャンする。
4. 商品のやり取り。
